### ISSUE TITLE
ACF 5.8+ - empty arrays in sync

### ISSUE THREAD

**Issue by gregsines** [superhuit-agency/wp-cli-acf-json#1]
Hi there

We have been using the acf-sync tool you have created and noticed it does not work with ACF 5.8+

The sync process which works in 5.7 or less creates empty arrays in ACF 5.8 and 5.9

Aware that the compatibility of the tool is 5.6.9 but would be great if this could be updated to work

Thanks

**Comment by hsmio** [comment]
Hey @gregsines thanks for reaching out. To be honest, we pretty much forgot about this tool, haven't used it since 2018. We won't be able to make time for fixing it at the moment, but we're happy to review a PR if you want to have a look at this compatibility issue. I noticed you closed the issue already so I guess you found another way around :)

Cheers,
Hugo
